### ISSUE TITLE
Click on cards doesn't open page

### ISSUE THREAD

**Issue by mf35** [fupdec/mediaChips#93]
**Describe the bug**
In the case i create a complex meta, then assign it to Videos in the "Videos" tab in settings:
Clicking on the newly added items of this new "meta page" doesn't lead to a page with header, avatar, whatever images plus filtered videos below.
Instead i have a black page with nothing.

This is resolved when i don't assign this complex meta page to Videos.
When i don't, the page, with pictures and videos, appears when i click on a card.
But therefore i can't link any of the items of this new complex meta to any videos.

**To Reproduce**
1. Settings > Meta > Add new complex meta > Let's call it "Girl Types" > Doesn't hide it in the menu
2. Click on this newly created "Girl Types" page in the menu > Add items in it like "Asian" and "Caucasian"
3. Go to the Videos page > Edit some videos and link some of the newly created items to them (add "Asian" and "Caucasian" where it's relevant)
4. Go back to the "Girl Types" page > Be sure that the data from the videos are updated, so i can see that i have now numbers in ( ) next to the items' names.
5. Left click on a card with some number in ( )

**Expected behavior**
The click should lead to a page with pictures and the videos on which i assigned the item just before.
Instead, it's a black page.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version 0.9.0

**Additional context**
The bug disappears when i don't assign "Girl Types" to Videos

**Comment by mf35** [comment]
Something to notice is that the already created pages i had before the update to 0.9.0, like the "Performer" page (meta), are assigned to Videos and when i click on their cards, it shows up the good page, with header and videos.

**Comment by fupdec** [comment]
Thanks for the detailed description. I found a bug and have already fixed it. I will be releasing a new release soon with a fix for this bug.
The good thing is that it doesn't affect user data in any way. The problem was counting the number of videos with added meta.

**Comment by mf35** [comment]
Hi, i tried the last patch.
The page is now opened properly, but no videos are filtered and none are showing.
It's empty or it is showing the result of the last filtering i did manually.

**Comment by draftvader** [comment]
> Hi, i tried the last patch.
> The page is now opened properly, but no videos are filtered and none are showing.
> It's empty or it is showing the result of the last filtering i did manually.

Same observation from me

**Comment by fupdec** [comment]
Strange, but it works for me. More data is needed to debug. But for some reason, in the latest versions of the Electron, it is not possible to open the developer tools. Previously, it was opened with the command Ctrl + Shift + I

**Comment by fupdec** [comment]
I figured out why the developer tools do not open. I removed the system menu that had a keyboard shortcut to open it. I will create a test build that opens the developer tools. Could you download this build and open it for yourself and then see the errors in the console? This will only work for windows.

**Comment by fupdec** [comment]
Link with test build: https://disk.yandex.ru/d/4Ic8NLkOymJA9Q

**Comment by fupdec** [comment]
Also feel free to reopen the issue if something doesn't work.

**Comment by mf35** [comment]
Hello, here is the error i got on the log, when i click a card to open a meta page:

chunk-vendors.ea5266c0.js:7 TypeError: Cannot read property 'includes' of undefined
    at chunk-4e82b6ec.d049012c.js:1
    at On (chunk-vendors.ea5266c0.js:15)
    at Function.iu [as filter] (chunk-vendors.ea5266c0.js:15)
    at f (chunk-vendors.ea5266c0.js:15)
    at Function.Kc [as thru] (chunk-vendors.ea5266c0.js:15)
    at chunk-vendors.ea5266c0.js:15
    at Nn (chunk-vendors.ea5266c0.js:15)
    at Ho (chunk-vendors.ea5266c0.js:15)
    at wr.eu (chunk-vendors.ea5266c0.js:15)
    at a.initVideoFilters (chunk-4e82b6ec.d049012c.js:1)
oe @ chunk-vendors.ea5266c0.js:7
ie @ chunk-vendors.ea5266c0.js:7
ne @ chunk-vendors.ea5266c0.js:7
(anonymous) @ chunk-vendors.ea5266c0.js:7
le @ chunk-vendors.ea5266c0.js:7
Promise.then (async)
ae @ chunk-vendors.ea5266c0.js:7
me @ chunk-vendors.ea5266c0.js:7
t.$nextTick @ chunk-vendors.ea5266c0.js:7
beforeMount @ chunk-vendors.ea5266c0.js:20
re @ chunk-vendors.ea5266c0.js:7
Fn @ chunk-vendors.ea5266c0.js:7
Dn @ chunk-vendors.ea5266c0.js:7
Or.$mount @ chunk-vendors.ea5266c0.js:7
init @ chunk-vendors.ea5266c0.js:7
p @ chunk-vendors.ea5266c0.js:7
d @ chunk-vendors.ea5266c0.js:7
b @ chunk-vendors.ea5266c0.js:7
d @ chunk-vendors.ea5266c0.js:7
b @ chunk-vendors.ea5266c0.js:7
d @ chunk-vendors.ea5266c0.js:7
(anonymous) @ chunk-vendors.ea5266c0.js:7
Mn.t._update @ chunk-vendors.ea5266c0.js:7
r @ chunk-vendors.ea5266c0.js:7
rr.get @ chunk-vendors.ea5266c0.js:7
rr @ chunk-vendors.ea5266c0.js:7
Dn @ chunk-vendors.ea5266c0.js:7
Or.$mount @ chunk-vendors.ea5266c0.js:7
init @ chunk-vendors.ea5266c0.js:7
n @ chunk-vendors.ea5266c0.js:7
p @ chunk-vendors.ea5266c0.js:7
d @ chunk-vendors.ea5266c0.js:7
C @ chunk-vendors.ea5266c0.js:7
N @ chunk-vendors.ea5266c0.js:7
C @ chunk-vendors.ea5266c0.js:7
N @ chunk-vendors.ea5266c0.js:7
(anonymous) @ chunk-vendors.ea5266c0.js:7
Mn.t._update @ chunk-vendors.ea5266c0.js:7
r @ chunk-vendors.ea5266c0.js:7
rr.get @ chunk-vendors.ea5266c0.js:7
rr.run @ chunk-vendors.ea5266c0.js:7
Qn @ chunk-vendors.ea5266c0.js:7
(anonymous) @ chunk-vendors.ea5266c0.js:7
le @ chunk-vendors.ea5266c0.js:7
Promise.then (async)
ae @ chunk-vendors.ea5266c0.js:7
me @ chunk-vendors.ea5266c0.js:7
er @ chunk-vendors.ea5266c0.js:7
rr.update @ chunk-vendors.ea5266c0.js:7
vt.notify @ chunk-vendors.ea5266c0.js:7
set @ chunk-vendors.ea5266c0.js:7
(anonymous) @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
ee.updateRoute @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
Bt @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
p @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
r @ chunk-vendors.ea5266c0.js:25
Bt @ chunk-vendors.ea5266c0.js:25
ee.confirmTransition @ chunk-vendors.ea5266c0.js:25
ee.transitionTo @ chunk-vendors.ea5266c0.js:25
e.push @ chunk-vendors.ea5266c0.js:25
(anonymous) @ chunk-vendors.ea5266c0.js:25
Te.push @ chunk-vendors.ea5266c0.js:25
openMetaCardPage @ chunk-ebe52834.8e94c126.js:2
re @ chunk-vendors.ea5266c0.js:7
n @ chunk-vendors.ea5266c0.js:7
Ji.o._wrapper @ chunk-vendors.ea5266c0.js:7

**Comment by fupdec** [comment]
I fixed the error and replaced the file in the cloud. Download it again and try it now please.

**Comment by mf35** [comment]
It is working now, thank you :)

**Comment by mf35** [comment]
Hi, with the last version (0.10.5), this bug has appeared again when i click on some cards.
Here is the log when i click on those cards:

TypeError: Cannot read property 'includes' of undefined
    at chunk-3cfdfc3e.86db984d.js:1
    at On (chunk-vendors.e1f3bf42.js:15)
    at Function.iu [as filter] (chunk-vendors.e1f3bf42.js:15)
    at f (chunk-vendors.e1f3bf42.js:15)
    at Function.Kc [as thru] (chunk-vendors.e1f3bf42.js:15)
    at chunk-vendors.e1f3bf42.js:15
    at kn (chunk-vendors.e1f3bf42.js:15)
    at Ho (chunk-vendors.e1f3bf42.js:15)
    at Sr.eu (chunk-vendors.e1f3bf42.js:15)
    at a.videoThumbImgUrls (chunk-3cfdfc3e.86db984d.js:1)

**Comment by fupdec** [comment]
I fixed that, soon will be a hotfix for app.

**Comment by mf35** [comment]
Thank you, i tried the hotfix but i still have a bug on the pages which was empty.
Now the content appears properly but the header picture doesn't.
Whatever i do, the header is always the placeholder with multpile thumbnails of the videos.

I can delete, replace the picture, through the app or manually through Windows Explorer, the picture doesn't appear.
I don't know what else to say becuse i have no errors in the log.
I tried to switch the new cosmetic header option on and off, it doesn't change.

The only thing usefull i can say is that it affects only the pages with which i had troubles displaying content.

**Comment by mf35** [comment]
I tried to create a new item and give it a header picture: no header picture appears.
I tried to create a new item, assign a video to it: the placeholder header was displayed. But when i added a header picture: nothing changed, still the placeholder.

Hope it can help you.

**Comment by mf35** [comment]
Hello :)
Any news on this bug ? Even with the last app version, no header picture want to appear.
I still have the placeholder picture with frames from videos.

I see it's still in progress, but did you find out what was wrong ?

**Comment by fupdec** [comment]
The header is not displayed when there is no alternative image. 
I had no problem with this because I usually add two images for each performer.

The header display code is a little confusing due to the abundance of the number of images and the possible options for customizing the meta.

If you are satisfied with this temporary solution, then I would prefer to close this issue. And in the future, after adding support for images to the application, the header will be greatly changed. Since I'm thinking of adding a slideshow to it based on the added pictures.

If you are not satisfied with this workaround, then I will still fix the display of the header in one of the next updates.

**Comment by mf35** [comment]
Oh you're right: no displayed header picture when no alternative picture exists.

Ok for now i can live with this workaround, thank you :)
